spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: pass
    driverClassName: org.h2.Driver
#    url: jdbc:h2:file:./data;
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true